apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: team-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: team-4
spec:
  selector:
    app: sample-app
  ports:
    - name: http
      port: 80
      targetPort: http