## Append samples of your project ##
resources:
- namespace.yaml
- stable-configmap.yaml
- canary-configmap.yaml
- stable-deployment.yaml
- stable-service.yaml
- deploy_v1alpha1_canaryrelease.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
