apiVersion: v1
kind: ConfigMap
metadata:
  name: stable-html
  namespace: team-5
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Demo App</title></head>
    <body>
      <h1>Stable v1.25</h1>
      <p>This is the stable version.</p>
    </body>
    </html>
