apiVersion: database.study.dev/v1
kind: MySQLInstance
metadata:
  name: my-mysql
  namespace: team-1
spec:
  version: "8.0"
  replicas: 1
  storageSize: "1Gi"
  rootPasswordSecret: mysql-root-secret
  initSQL:
    - CREATE DATABASE appdb
    - CREATE TABLE users (id INT PRIMARY KEY, name VARCHAR(255))

  backupSchedule: "0 */6 * * *"